<!DOCTYPE html>
<html lang="pl">
	<head>
		<meta charset="utf-8">

	
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title></title>
		<meta name="description" content="">
		<meta name="author" content="f1">

		<meta name="viewport" content="width=device-width; initial-scale=1.0">
  		
		<link rel="shortcut icon" href="/favicon.ico">
		<link rel="stylesheet" href="styl.css" type="text/css"/>
	</head>

	<body>
		<div>
			<header>
				&nbsp;
			</header>
			<div id="konterner">
			